FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn -q -DskipTests package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

COPY --from=build /app/target/signaldesk.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
